### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by iop3** [infinitygamer404/infinitygamer404#5]
> - ⚡ Fun fact: I sneeze a lot, but you didn't have to know that

*looks at news*

***:O covid***

*looks back at ur readme*

***:O you sneeze a lot***

**FREAK OUT**

**Comment by infinitygamer404** [comment]
> > * ⚡ Fun fact: I sneeze a lot, but you didn't have to know that
> 
> _looks at news_
> 
> _**:O covid**_
> 
> _looks back at ur readme_
> 
> _**:O you sneeze a lot**_
> 
> **FREAK OUT**

lol don't freak out
i have had sinusitis since a was a wee lil lad
it makes me sneeze thousands of times each month
it's definitely not covid-19

**Comment by iop3** [comment]
ok lul

**Comment by Benjimanrich** [comment]
> ok lul

@iop3 sneezing isn't just limited to covid, also check the last update date of this repo, there's no way covid would last that long.

**Comment by TheQuackyDuck** [comment]
it was just a joke smh
