### ISSUE TITLE
Knock knock

### ISSUE THREAD

**Issue by thehiddencoder001** [infinitygamer404/infinitygamer404#6]
Hello, its been a few weeks since we have last heard from you. Just wondering if everything's alright.
Totally not thecoder001 btw.

**Comment by Benjimanrich** [comment]
@thehiddencoder001 he's alive check his star history also come online @infinitygamer404

**Comment by infinitygamer404** [comment]
everything is fine
I've just been a little busy with some study and i spent most of my free time watching anime and youtube and stuff
I'll be online soon-ish

**Comment by Benjimanrich** [comment]
ok lol

**Comment by thehiddencoder001** [comment]
Good to hear! See ya soon ig.
![image](https://user-images.githubusercontent.com/74935242/131369499-6ffa45f5-2e7e-40eb-aee2-77a0a8d79d27.png)
